# Generated by Django 5.2 on 2026-07-10 15:12

import core.mixins.slug
import core.utils.upload
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=150, verbose_name='نام برند')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=core.utils.upload.UploadToPath('brand'), verbose_name='لوگو')),
                ('is_featured', models.BooleanField(default=False, verbose_name='برند ویژه')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['name'],
            },
            bases=(core.mixins.slug.SlugMixin, models.Model),
        ),
    ]
