# Generated by Django 5.2 on 2026-07-11 20:22

import core.mixins.slug
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_attribute_attributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand', verbose_name='برند')),
                ('categories', models.ManyToManyField(related_name='products', to='store.category', verbose_name='دسته بندی ها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
            bases=(core.mixins.slug.SlugMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='بارکد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن (گرم)')),
                ('is_default', models.BooleanField(default=False, verbose_name='واریانت پیش\u200cفرض')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'واریانت',
                'verbose_name_plural': 'واریانت\u200cها',
                'ordering': ['product', '-is_default', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_attributes', to='store.attributevalue', verbose_name='مقدار ویژگی')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='store.variant', verbose_name='واریانت')),
            ],
            options={
                'verbose_name': 'ویژگی واریانت',
                'verbose_name_plural': 'ویژگی\u200cهای واریانت',
                'ordering': ['variant'],
                'constraints': [models.UniqueConstraint(fields=('variant', 'attribute_value'), name='unique_variant_attribute')],
            },
        ),
    ]
