# Generated by Django 5.2 on 2026-08-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='attribute_type',
            field=models.CharField(choices=[('color', 'رنگ'), ('size', 'سایز'), ('material', 'جنس'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, help_text='این فیلد به صورت هوشمند توسط سیستم ثبت میشود(لازم نیست مقداری وارد نمایید)', max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='این فیلد به صورت هوشمند توسط سیستم ثبت میشود(لازم نیست مقداری وارد نمایید)', max_length=200, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='این فیلد به صورت هوشمند توسط سیستم ثبت میشود(لازم نیست مقداری وارد نمایید)', max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]
