# Generated by Django 5.2 on 2026-08-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, help_text='این فیلد به صورت اتوماتیک توسط سایت تکمیل میگردد (نیازی به وارد کردن مقداری نیست) ', max_length=255, unique=True, verbose_name='اسلاگ'),
        ),
    ]
