# Generated by Django 5.2 on 2026-09-03 16:55

import core.utils.upload
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='hkljklj', upload_to=core.utils.upload.UploadToPath('category')),
            preserve_default=False,
        ),
    ]
