# Generated by Django 5.2 on 2026-08-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=100, verbose_name='عنوان کوچک')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان اصلی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='متن دکمه')),
                ('button_url', models.CharField(blank=True, max_length=255, verbose_name='لینک دکمه')),
                ('desktop_image', models.ImageField(upload_to='sliders/desktop/', verbose_name='تصویر دسکتاپ')),
                ('mobile_image', models.ImageField(blank=True, null=True, upload_to='sliders/mobile/', verbose_name='تصویر موبایل')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
