# Generated by Django 5.2 on 2026-08-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimageprompt',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='پرامپت فعال'),
        ),
    ]
