# Generated by Django 5.2 on 2026-08-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiimageprompt_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimageprompt',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
